name: pr

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          echo  omidiyanto1234567 | docker login docker.io -u omidiyanto --password-stdin
          docker build . --file Dockerfile --tag omidiyanto/flask-weatherapp:${{ github.event.pull_request.head.sha }}
          docker push omidiyanto/flask-weatherapp:${{ github.event.pull_request.head.sha }}
  

  update-image-tag:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - run: |
          echo "cloning gitops repo" && git clone https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/omidiyanto/flask-weatherapp.git
          cd flask-weatherapp
          git config --global user.email ci-bot@argocd.com && git config --global user.name ci-bot
          echo "checkout source branch"
          git checkout ${{ github.event.pull_request.head.ref }}
          echo "updating image tag in values.yaml"
          sed -i "s,tag:.*,tag:\ ${{ github.event.pull_request.head.sha }}," helm/flask-weatherapp/values.yaml
          git add . && git commit -m "update image tag to ${{ github.event.pull_request.head.sha }}"
          git push

  add_labels:
    runs-on: ubuntu-latest
    needs: update-image-tag
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: label to preview
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: | 
          preview
      
