name: pr

on:
  pull_request:
    branches: [ "master" ]

# Beri izin agar GITHUB_TOKEN bisa memberi label dan push commit
permissions:
  contents: write       # untuk git push
  pull-requests: write  # untuk menambah label PR

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          echo omidiyanto1234567 | docker login docker.io -u omidiyanto --password-stdin
          docker build . --file Dockerfile --tag omidiyanto/flask-weatherapp:${{ github.event.pull_request.head.sha }}
          docker push omidiyanto/flask-weatherapp:${{ github.event.pull_request.head.sha }}

  update-image-tag:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Clone gitops repo with token
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/omidiyanto/flask-weatherapp.git gitops
      - name: Update image tag in values.yaml & skip CI
        run: |
          cd gitops
          git config user.email "ci-bot@argocd.com"
          git config user.name  "ci-bot"
          git checkout ${{ github.event.pull_request.head.ref }}
          sed -i "s,tag:.*,tag: ${{ github.event.pull_request.head.sha }}," helm/flask-weatherapp/values.yaml
          git add helm/flask-weatherapp/values.yaml
          # Tambahkan [skip ci] agar commit ini tidak memicu pipeline lagi
          git commit -m "ci: update image tag to ${{ github.event.pull_request.head.sha }} [skip ci]"
          git push

  add_labels:
    runs-on: ubuntu-latest
    needs: update-image-tag
    steps:
      - name: Checkout (required by action-add-labels)
        uses: actions/checkout@v4
      - name: Label to preview
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: preview
          repo: omidiyanto/flask-weatherapp
